# -*- makefile -*-
export builddir = /home/zzl/ovs/datapath/linux
export srcdir = /home/zzl/ovs/datapath/linux
export top_srcdir = /home/zzl/ovs
export VERSION = 2.1.2

include $(srcdir)/../Modules.mk
include $(srcdir)/Modules.mk

EXTRA_CFLAGS := -DVERSION=\"$(VERSION)\"
EXTRA_CFLAGS += -I$(srcdir)/..
EXTRA_CFLAGS += -I$(builddir)/..
EXTRA_CFLAGS += -g
EXTRA_CFLAGS += -include $(builddir)/kcompat.h

# These include directories have to go before -I$(KSRC)/include.
# NOSTDINC_FLAGS just happens to be a variable that goes in the
# right place, even though it's conceptually incorrect.
NOSTDINC_FLAGS += -I$(top_srcdir)/include -I$(srcdir)/compat -I$(srcdir)/compat/include

obj-m := $(patsubst %,%.o,$(build_modules))

define module_template
$(1)-y = $$(notdir $$(patsubst %.c,%.o,$($(1)_sources)))
endef

$(foreach module,$(build_modules),$(eval $(call module_template,$(module))))
